#!/bin/bash
DIR=$(pwd)	

trap ctrl_c INT

function ctrl_c() {
        echo "** Trapped CTRL-C"
}

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac
echo ${machine}

if [ ${machine} == "Linux" ]
then
	echo "Running programs in Linux Enviroment"
	if [ "$1" == "clean" ] 
	then
		echo "Clean up all folders.."
		find -type d -name build -prune -exec rm -rf {} \;
	else
		if [ "$1" != "" ]
		then
			echo "Ignoring extra arguments.."
		fi
		
		cd Computational_App	
		echo "Running Projects in Computational_App Folder"
		./Run
		cd ../

		cd Hanoi_Simulation
		echo "Running Projects in Hanoi_Simulation Folder"
		./Run
		cd ../

		cd Telephone_List
		echo "Running Projects in Telephone_List Folder"
		./Run
		cd ../

		cd Matrix_Max_Summary
	    echo "Running Projects in Matrix_Max_Summary Folder"
		./Run
		cd ../
		cd ../

	fi
fi
