#!/bin/bash
DIR=$(pwd)			

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac
echo ${machine}

if [ ${machine} == "Linux" ]
then
	echo "Running programs in Linux Enviroment"
	if [ "$1" == "clean" ] 
	then
		echo "Clean up.."
		rm -rfv Hanoi/build/*
	else
		if [ "$1" != "" ]
		then
			echo "Ignoring extra arguments.."
		fi
		echo "Running project.."
		echo "CMake Building for Hanoi Numbers.."
		cd Hanoi
		mkdir build
		cd build
		cmake ..
		echo "CMake Build done"
		echo "Build project..."
		make
		echo "Build done..."
		echo "-Running Hanoi simulation..."
		echo "------------------------ Hanoi simulation ------------------------"
		./Hanoi;
		echo "------------------------------------------------------------------" 
	fi
fi
